import type { Metadata } from "next";
import Navbar from "@/components/Shared/Navbar";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Md Junayed | Protfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=" ">
      <Navbar />
      <TooltipProvider>{children}</TooltipProvider>
    </div>
  );
}
