import type { Metadata } from "next";
import { TracingBeam } from "@/components/ui/tracing-beam";
import Navbar from "@/components/Shared/Navbar";



export const metadata: Metadata = {
  title: "Md Junayed | Protfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
        <div className=" overflow-y-hidden">
          <Navbar />
          <TracingBeam className="">
            {children}
            </TracingBeam>
        </div>
      
  );
}
