import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/Porviders";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Md Junayed | Protfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={` bg-slate-900  antialiased`}
      >
        <div className=" overflow-y-hidden">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
