export const technologies = [
    { id: 1, name: "Angular" },
    { id: 2, name: "Ant Design" },
    { id: 3, name: "Apollo Client" },
    { id: 4, name: "Apollo Server" },
    { id: 5, name: "AppSignal" },
    { id: 6, name: "AWS" },
    { id: 7, name: "AWS Lambda" },
    { id: 8, name: "Azure" },
    { id: 9, name: "Azure Functions" },
    { id: 10, name: "Babel" },
    { id: 11, name: "Bitbucket" },
    { id: 12, name: "Bootstrap" },
    { id: 13, name: "Cassandra" },
    { id: 14, name: "Capacitor" },
    { id: 15, name: "CircleCI" },
    { id: 16, name: "Chai" },
    { id: 17, name: "Cloudflare" },
    { id: 18, name: "CockroachDB" },
    { id: 19, name: "Contentful" },
    { id: 20, name: "Cypress" },
    { id: 21, name: "Docker" },
    { id: 22, name: "Docker Compose" },
    { id: 23, name: "Electron" },
    { id: 24, name: "Elasticsearch" },
    { id: 25, name: "Ember.js" },
    { id: 26, name: "ESLint" },
    { id: 27, name: "Expo" },
    { id: 28, name: "Express" },
    { id: 29, name: "Express.js" },
    { id: 30, name: "FastAPI" },
    { id: 31, name: "Firebase" },
    { id: 32, name: "Firebase Auth" },
    { id: 33, name: "Firebase Firestore" },
    { id: 34, name: "Firebase Hosting" },
    { id: 35, name: "Figma" },
    { id: 36, name: "Flutter" },
    { id: 37, name: "FlutterFlow" },
    { id: 38, name: "Framer" },
    { id: 39, name: "Gatsby" },
    { id: 40, name: "Git" },
    { id: 41, name: "GitHub" },
    { id: 42, name: "GitLab" },
    { id: 43, name: "GitOps" },
    { id: 44, name: "GraphQL" },
    { id: 45, name: "GraphQL Codegen" },
    { id: 46, name: "GraphQL Playground" },
    { id: 47, name: "Heroku" },
    { id: 48, name: "HTML" },
    { id: 49, name: "Ionic" },
    { id: 50, name: "InVision" },
    { id: 51, name: "Jenkins" },
    { id: 52, name: "Jest" },
    { id: 53, name: "Joi" },
    { id: 54, name: "Joomla" },
    { id: 55, name: "JQuery" },
    { id: 56, name: "Kubernetes" },
    { id: 57, name: "Laravel" },
    { id: 58, name: "Laravel" },
    { id: 59, name: "Material UI" },
    { id: 60, name: "Magento" },
    { id: 61, name: "Mocha" },
    { id: 62, name: "MongoDB" },
    { id: 63, name: "MongoDB Atlas" },
    { id: 64, name: "MySQL" },
    { id: 65, name: "NATS" },
    { id: 66, name: "NestJS" },
    { id: 67, name: "Netlify" },
    { id: 68, name: "Nginx" },
    { id: 69, name: "Next.js" },
    { id: 70, name: "NextAuth.js" },
    { id: 71, name: "Nuxt.js" },
    { id: 72, name: "OracleDB" },
    { id: 73, name: "Playwright" },
    { id: 74, name: "Postman" },
    { id: 75, name: "Prisma" },
    { id: 76, name: "Prismic CMS" },
    { id: 77, name: "Puppeteer" },
    { id: 78, name: "RabbitMQ" },
    { id: 79, name: "Rails" },
    { id: 80, name: "React" },
    { id: 81, name: "React Native" },
    { id: 82, name: "React Testing Library" },
    { id: 83, name: "Redis" },
    { id: 84, name: "Redux" },
    { id: 85, name: "Recoil" },
    { id: 86, name: "Ruby on Rails" },
    { id: 87, name: "REST API" },
    { id: 88, name: "Sanity" },
    { id: 89, name: "SASS" },
    { id: 90, name: "Sentry" },
    { id: 91, name: "Shopify" },
    { id: 92, name: "Socket.io" },
    { id: 93, name: "Spring Boot" },
    { id: 94, name: "Strapi" },
    { id: 95, name: "Storybook" },
    { id: 96, name: "Supabase" },
    { id: 97, name: "Tailwind CSS" },
    { id: 98, name: "Terraform" },
    { id: 99, name: "Three.js" },
    { id: 100, name: "Tauri" },
    { id: 101, name: "TypeScript" },
    { id: 102, name: "Vercel" },
    { id: 103, name: "Vue" },
    { id: 104, name: "Vuex" },
    { id: 105, name: "Webpack" },
    { id: 106, name: "WebAssembly" },
    { id: 107, name: "WebRTC" },
    { id: 108, name: "WebSockets" },
    { id: 109, name: "WooCommerce" },
    { id: 110, name: "WordPress" },
    { id: 111, name: "Zod" },
    { id: 112, name: "Zustand" }
  ];
  